# Generated by Django 3.0.6 on 2020-05-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20200530_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flexible Page', 'verbose_name_plural': 'Flexible Pages'},
        ),
    ]
