# Generated by Django 3.0.6 on 2020-05-30 20:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subjectlandingpage_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectlandingpage',
            options={'verbose_name': 'Subject Overview Page', 'verbose_name_plural': 'Subject Overview Pages'},
        ),
        migrations.CreateModel(
            name='SubjectKeyStageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', wagtail.core.fields.RichTextField(max_length=1)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_stage_card', to='subject.SubjectLandingPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
