# Generated by Django 3.0.6 on 2020-05-30 20:28

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20200530_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectkeystagecard',
            name='description',
            field=wagtail.core.fields.RichTextField(default='Test', help_text='Enter information about what this Key Stage covers', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectkeystagecard',
            name='title',
            field=models.CharField(help_text='Enter the Key Stage Level', max_length=20),
        ),
    ]
