# Generated by Django 3.0.6 on 2020-06-04 16:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('subject', '0006_subjectkeystagecard_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectkeystagecard',
            name='content',
            field=wagtail.core.fields.StreamField([('test', wagtail.core.blocks.StructBlock([('module_name', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, help_text='Select Module', required='True')), ('module_information', wagtail.core.blocks.CharBlock(help_text='Add Module Information', required=True))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubjectKSLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField(help_text='Please insert a short description as to what this Key Stage covers', max_length=200, null=True)),
                ('image', models.ForeignKey(help_text='This will be used on the listing page and will be cropped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('internal_page', models.ForeignKey(blank=True, help_text='Set an internal page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
