# Generated by Django 3.0.6 on 2020-06-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20200604_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectkslandingpage',
            options={'verbose_name': 'Key Stage Description for Subject'},
        ),
    ]
